### ISSUE TITLE
Maven Parent Module

### ISSUE THREAD

**Issue by pbelmann** [jkrue/jobproxy#1]
We should split the existing project in different subprojects:

* JobProxyInterfaces  :  Model classes that must be implemented.
* JobProxyChronos : Chronos JobProxy implementation
* JobProxy : Main Class that add dependencies to the existing Implementations (JobProxyChronos, ....)

**Comment by pbelmann** [comment]
@jkrue  

I think we should change groupId de.unibi.cebitec.bibiserv.jkrueger to de.unibi.cebitec.bibiserv
and package names from de.unibi.cebitec.bibiserv to de.unibi.cebitec.

What do you think?

**Comment by jkrue** [comment]
I agree for the group id, but disagree for the package names - in my opinion de.unibi.cebitec is too general ... why not choosing the same identifier for group id and package names ?

**Comment by pbelmann** [comment]
how about de.unibi.cebitec.jobproxy ?

**Comment by pbelmann** [comment]
I tested it with the helloworld and it works.
