### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by tlaufkoetter** [jkrue/jobproxy#24]
* errors should at least result in the appropriate HTTP response status code
    * suggestions:
        * 400 - bad request (in case of input error)
        * 502 - bad gateway (in case of a missing mesos scheduler)

**Comment by pbelmann** [comment]
I add basic validation for submitted tasks using javax api. 
Bad gateway error is produced if the response of the implementing framework has not successful "2xx" status code.

This implementation needs more testing (see #36 )
