### ISSUE TITLE
Cannot submit a container to be started

### ISSUE THREAD

**Issue by tlaufkoetter** [jkrue/jobproxy#30]
Chronos response has the status 500.

**Comment by pbelmann** [comment]
I could not reproduce this error. 
If this is the fault of your chronos configuration I created issue #38 in order to show the configuration that definitely works with jobproxy.

Please reopen if you still encounter this issue.

**Comment by pbelmann** [comment]
By the way the following xml works for me:

~~~
<task>
    <user>test</user>
    <cores>1</cores>
    <memory>128</memory>
    <cputime>10</cputime>
    <cmd>sleep 40</cmd>
    <container>
            <image>ubuntu</image>
    </container>
</task>
~~~
