### ISSUE TITLE
Framework Configuration

### ISSUE THREAD

**Issue by pbelmann** [jkrue/jobproxy#47]
Each framework needs a different kind of Configuration.

Example:

  * Mesos based frameworks need zookeeper url

  * Java Docker needs the path to docker.sock or the url

We need a configuration interface that each framework implements.

This interface should for example demand

  * that the configuration is exposed with a to string option. 

  * that the name of the framework is reported.

**Comment by jkrue** [comment]
Integrated in commit '6c2fc9e7db6a14ba6281bd7d0efc0d77d9791f0b'. Each Framework get an optional Properties object, which contains framework specific properties but also general options (like server URI)
