### ISSUE TITLE
List available Frameworks

### ISSUE THREAD

**Issue by pbelmann** [jkrue/jobproxy#53]
JobProxyServer should be able to list all available frameworks.
We need a REST Endpoint and a JobProxyServer call.

**Comment by jkrue** [comment]
I don't get it. 
I agree that the JobProxyServer[CLI] should list all available frameworks/plugins (all implementions of JobProxyInterface) within the classpath. But why should we have a REST endpoint for such a function ? For a possible client it doesnt make any difference which Framework is used to handle its request.

**Comment by jkrue** [comment]
@pbelmann The 'list' functionality could be easily implemented. Currently the list of framework is hard coded in the JobProxyServer[CLI] class, which makes it impossible to use JobProxy with external Framework implementation without recompilation. We should implement a more  dynamic approach. Reflections ( https://github.com/ronmamo/reflections ) looks like it that it could help us to solve this problem. What do you think ?

**Comment by pbelmann** [comment]
> But why should we have a REST endpoint for such a function ? For a possible client it doesnt make any difference which Framework is used to handle its request.

Well I agree.  for a client is doesn't matter what kind of frameworks are available. Maybe just what kind of framework is currently used?

> @pbelmann The 'list' functionality could be easily implemented. Currently the list of framework is hard coded in the JobProxyServer[CLI] class, which makes it impossible to use JobProxy with external Framework implementation without recompilation. We should implement a more dynamic approach. Reflections ( https://github.com/ronmamo/reflections ) looks like it that it could help us to solve this problem. What do you think ?

Yes I also would like to add frameworks without recompiling the jobproxy. Reflections is here the way to go.

**Comment by pbelmann** [comment]
Maybe we should open a different issue for using reflections in jobproxy?

**Comment by jkrue** [comment]
Feature "list available fameworks" is now integrated in beta.1.release; solved using Reflections ( https://github.com/ronmamo/reflections )
