### ISSUE TITLE
mvn 3.0 vs . mvn 3.3 // resolve dependency problems

### ISSUE THREAD

**Issue by jkrue** [jkrue/jobproxy#66]
Currently only maven  3.0.x creates a full functional running shaded jar. Building a shaded jar with mvn 3.3.x leads to a nonfunctional jar. Maven reports during packaging a lot of overlapping classes, which all comes from a com.spotify#docker-client dependency (depends on an outdated jackson.core#databind and maybe other libs). A fast solution is to remove any dependency to the JobProxyJavaDocker module. However we have to find a good solution to resolve such dependency problems ...

**Comment by pbelmann** [comment]
With PR #68 this might be fixes. We have to test it first with both maven versions.

**Comment by jkrue** [comment]
Good work! Try both versions (3.0.4 from NB and 3.3.9), works!

**Comment by pbelmann** [comment]
Thanks! I'm happy to hear that! :-)
